sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Projectile, function (sprite, otherSprite) {
    story.spriteSayText(mySprite2, "ouch", 15, 13, story.TextSpeed.VerySlow)
    statusbar.value += -10
    tiles.placeOnRandomTile(otherSprite, sprites.castle.tilePath5)
})
function startbattle () {
    info.setLife(5)
    mySprite = sprites.create(img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . . f e 2 f f f f f f 2 e f . . 
        . . f f f f e e e e f f f f . . 
        . f f e f b f 4 4 f b f e f f . 
        . f e e 4 1 f d d f 1 4 e e f . 
        . . f e e d d d d d d e e f . . 
        . . . f e e 4 4 4 4 e e f . . . 
        . . e 4 f 2 2 2 2 2 2 f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `, SpriteKind.Player)
    mySprite2 = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    statusbar = statusbars.create(50, 5, StatusBarKind.Health)
    statusbar.attachToSprite(mySprite2)
    tiles.setCurrentTilemap(tilemap`level1`)
    mySprite3 = sprites.create(img`
        . . . . . . . . f f . . . . . . 
        . . . . . . . f f f . . . . . . 
        . . . . . . f f 4 f . . . . . . 
        . . . . . . f 4 4 4 f . . . . . 
        . . . . . . f 4 4 4 4 f . . . . 
        . . . . . f 4 4 4 4 4 f . . . . 
        . . . . . f 4 4 4 4 4 f . . . . 
        . . . . . f 4 4 4 4 4 4 f . . . 
        . . . . f 4 4 4 4 4 4 4 f . . . 
        . . . . f 4 4 4 4 4 4 4 f . . . 
        . . . . f 4 4 4 4 4 4 4 f . . . 
        . . . f 4 4 4 4 4 4 4 4 4 f . . 
        . . . f 4 4 4 4 4 4 4 4 4 f . . 
        . . . f 4 4 4 4 4 4 4 4 4 f . . 
        . . . f 4 4 4 4 4 4 4 4 4 f . . 
        . . . . f f f f f f f f f . . . 
        `, SpriteKind.Projectile)
    tiles.placeOnTile(mySprite, tiles.getTileLocation(10, 5))
    tiles.placeOnTile(mySprite2, tiles.getTileLocation(16, 1))
    tiles.placeOnRandomTile(mySprite3, sprites.castle.tilePath5)
    controller.moveSprite(mySprite)
    scene.cameraFollowSprite(mySprite)
    mySprite2.follow(mySprite, 70)
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    animation.runImageAnimation(
    mySprite2,
    [img`
        ........................
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .....fffc1111111f.......
        ...fc111cd1111111f......
        ...f1b1b1b1111dddf......
        ...fbfbffcf11fcddf......
        ......fcf111111bbf......
        .......ccbdb1b1fcf......
        .......fffbfbfdff.......
        ........ffffffff........
        ........fffffffffff.....
        .........fffffc111cf....
        .........fffff1b1b1f....
        ..........ffffbfbfbf....
        ...........ffff.........
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ....7.fd11111111df......
        ...7..fd11111111df......
        ...7..fd11111111df......
        ...7..fddd1111dddff.....
        ...77.fbdbfddfbdbfcf....
        ...777fcdcf11fcdcfbf....
        ....77fffbdb1bdffcf.....
        ....fcb1bcffffff........
        ....f1c1c1ffffff........
        ....fdfdfdfffff.........
        .....f.f.f..............
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd111111111f......
        ......fd11111111df......
        ......fd11111111df......
        ......fcdd1111ddcff.....
        .......fbcf11fcbfbbf....
        .......ffbdb1bdffff.....
        ........fcbfbfdf........
        ........ffffffff........
        ......ffffffffff........
        .....fcb1bcffff.........
        ......ffbff.............
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fdd111111ddf......
        ......fbdd1111dddf......
        ......fcdbfddfbdbf......
        .......fbcf11fcbfff.....
        .......ffb1111bcfbcf....
        ........fcdb1bdfbbbf....
        .......ffffffffffcf.....
        .....fcb1bcfffff........
        .....f1b1b1ffff.........
        ......ffbff.............
        ........................
        ........................
        ........................
        ........................
        ........................
        `],
    100,
    false
    )
    story.spriteSayText(mySprite2, "gotchu", 15, 13, story.TextSpeed.Fast)
    info.changeLifeBy(-1)
    tiles.placeOnTile(mySprite2, tiles.getTileLocation(16, 1))
})
let mySprite3: Sprite = null
let mySprite: Sprite = null
let statusbar: StatusBarSprite = null
let mySprite2: Sprite = null
story.startCutscene(function () {
    story.printDialog("Boss: Hello mortal, you dare challenge me? You know that people who have tried to defeat me have all failed, and you dare challenge me.", 80, 90, 50, 150)
    story.printDialog("You: don't care LMAO", 80, 90, 50, 150)
    startbattle()
})
